apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app intel-device-plugin-operator
  namespace: kube-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/kube-system/intel-device-plugin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 3m
  timeout: 2m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app intel-device-plugin-gpu
  namespace: &namespace kube-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: intel-device-plugin-operator
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
    - apiVersion: deviceplugin.intel.com/v1
      kind: GpuDevicePlugin
      name: i915
  healthCheckExprs:
    - apiVersion: deviceplugin.intel.com/v1
      kind: GpuDevicePlugin
      failed: status.desiredNumberScheduled != status.numberReady
      current: status.desiredNumberScheduled == status.numberReady
  interval: 1h
  path: ./kubernetes/apps/kube-system/intel-device-plugin-operator/gpu
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
