# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:GM4ykSnrkmS72/HGEA1zjDReAmiKuKBHX4l/sSLkTWo=,iv:vuFIpSJzqY/OOTwSimuekryFH6uHy3qkcLRsvHXFpM8=,tag:ljY/h1bbZkGivJEzV/QtjA==,type:str]
sops:
  age:
    - recipient: age1qzzw37sv7ctnmgv6jlu5k8063y5drskzzdwzvz3fc05vkwsuxefq7wwqxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbllOaVdMS2Z3N0pJWDFm
        T3VBWElBY3BMTUVZWXFKa1huOWFNY05JT0VnCnNMOXlVMnVISGppZlExNFhpOTJq
        dUM4T2NiNkV0VnVmcFBXT0tRb3FHa3cKLS0tIFdhQWtFTm9HM05LUEhCTXFNUDlR
        TGZ2d1R3RXdoU0pENEtlbDMyNGVXWFEKOs7E21UCWXLDbMYQI1ChjAHSr8FkEt+a
        XzqLNsJclObe5CSmAUeMBToe1P+yg6Iz8gRfl3dAKsgxxZLE5lzbUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T08:41:53Z"
  mac: ENC[AES256_GCM,data:Sl8MMC5Xw7LVzzN+zSN2P1O9ainOiOKH6DoOHzeEN4bQ/z2SkWhQv0kLkAi6yAf7ajUcgL/Gb/o55ht6KNhV0Vm3IHRZIMewK9AcJJzjLYJ27Lk615U3tU05IyUACvq94j30ysthxya4nQF7w21T0H0Lr2beVKB/EIM13f/Yb70=,iv:msytAuzTwji5NCa2jlidR82VnZ6QqzHg4+qsbZfT6Y8=,tag:nzIRikDs6O4A+PA/P4hKlA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
