# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:0bKaE5ie+rHL1kCWMEzlCKzd/y8ep83YrhcQt1MI85M=,iv:9sXbyYsjgKQysqNlOyJHFXJozvTYpm7NAPmmcmlU7pY=,tag:UBNkV9t4CurQd8kkoES/hw==,type:str]
sops:
  age:
    - recipient: age1qzzw37sv7ctnmgv6jlu5k8063y5drskzzdwzvz3fc05vkwsuxefq7wwqxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VG5VRUkyS2dUczJVdmY2
        S0FMT3NyM3ZmRDVDWDNqdE9lTEpDVStKU1EwCkdGV0dIcWtSUDNVZWdPdnlJMHE4
        OFdQbWVteGJiUlZuUFE2VW43MmJXR00KLS0tIHZBSGNqcTdIWDNVUlBveTBhVDNl
        ZWU3VGJmVnNyWnIxbGc1Si9NeHVVczgKhgnvB4Vpv4+wsy52kH5yBx7PHXvaryr9
        Vvk8Rfch0ek89LXLauLBgcLcBZfxy3YvBwLUX7QA+UgsGr3TH1dABw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-05T09:55:39Z"
  mac: ENC[AES256_GCM,data:PRtxbAMiGBmKnZbxL0BoaQr6F8ErPfoQyo4Q2dB4U/f58TBrrrqP3xRHurP7S4z4jFgepRU64LvGfaqS0OY3KEEuZ3WbrOZ/lYd+l6fKgeaXXNaFc1aHP29j5HZbk16m50bCBWZD6KyfnPJI81K/uqn5mEITZ/HQEk1/YaLuIkc=,iv:Pi9JdyNIM7qbgiynKtIx/EIVtas1IOxA9tc5C5Er1G4=,tag:5ZixHI1fee+kSBrHHxUlbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
