apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/common
resources:
  - ./flaresolverr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./metube/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./sonarr/ks.yaml
  - ./bazarr/ks.yaml
