apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app volsync
  namespace: flux-system
spec:
  targetNamespace: volsync-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/volsync-system/volsync/app
  prune: true
  dependsOn:
    - name: snapshot-controller
      namespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 3m
  timeout: 2m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
