---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./echo/ks.yaml
  - ./syncthing/ks.yaml
  - ./pairdrop/ks.yaml
  - ./mapi/ks.yaml
  - ./code-server/ks.yaml
  - ./copyparty/ks.yaml
  - ./thelounge/ks.yaml
  - ./timetagger/ks.yaml
  - ./roundcube/ks.yaml
