---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m0s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.16
            env:
              PUSHOVER_DEBUG: "false"
              PUSHOVER_PRIORITY: 0
              SONARR__AUTHENTICATION_METHOD: none
              SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              SONARR__PORT: &port 80
              TZ: America/Los_Angeles
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 25m
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
                allowPrivilegeEscalation: false
                capabilities: { drop: ["ALL"] }
                readOnlyRootFilesystem: true
        pod:
          automountServiceAccountToken: false
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dot-hex.xyz"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        enabled: true
        existingClaim: sonarr
      data:
        type: nfs
        path: /mnt/main/media
        server: nas.dot-hex.xyz
        globalMounts:
          - path: /data/nas-media
      tmp:
        type: emptyDir
