---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tachidesk
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        EXTENSION_REPOS: "{{ .EXTENSION_REPOS }}"
  dataFrom:
    - extract:
        key: tachidesk
