---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tachidesk
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m0s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v2.1.1960@sha256:7124bbd28d639befa83296d1b5b300bc37b02468564a824921fd932f885eaaa6
            env:
              AUTO_DOWNLOAD_CHAPTERS: true
              BIND_PORT: &port 4567
              DEBUG: true
              DOWNLOAD_AS_CBZ: false
              EXTENSION_REPOS: '["https://github.com/keiyoushi/extensions/tree/repo"]'
              JAVA_TOOL_OPTIONS: -XX:+UseG1GC -XX:MaxRAMPercentage=75 -XX:+PrintFlagsFinal
              TZ: America/Los_Angeles
              FLARESOLVERR_ENABLED: true
              FLARESOLVERR_URL: http://flaresolverr.downloads.cluster.svc.local.
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFileSystem: true
            probes:
              liveness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /manifest.json
                    port: 4567
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /manifest.json
                    port: 4567
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 1
    defaultPodOptions:
          automountServiceAccountToken: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: {type: RuntimeDefault}
    persistence:
      config:
        enabled: true
        existingClaim: tachidesk-config
        globalMounts:
        - path: /home/suwayomi/.local/share/Tachidesk
      downloads:
        enabled: true
        globalMounts:
        - path: /mnt
        path: /mnt/main/manga-share
        server: nas.dot-hex.xyz
        type: nfs
    service:
      app:
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dot-hex.xyz"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
