---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tachidesk
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m0s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v2.1.2087@sha256:87407b67902e3be2bcef11fada1f67b12f71b14fa8a205d870e24f64ac613240
            env:
              - name: AUTO_DOWNLOAD_CHAPTERS
                value: true
              - name : BIND_PORT
                value: &port 4567
              - name: DEBUG
                value: true
              - name: DOWNLOAD_AS_CBZ
                value: true
              - name: TZ
                value: America/Los_Angeles
              - name: FLARESOLVERR_ENABLED
                value: true
              - name: FLARESOLVERR_URL
                value: http://flaresolverr.downloads.svc.cluster.local:8191
              - name: EXTENSION_REPOS
                valueFrom:
                  secretKeyRef:
                    name: tachidesk
                    key: EXTENSION_REPOS
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFileSystem: true
            probes:
              liveness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /manifest.json
                    port: 4567
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /manifest.json
                    port: 4567
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 1
    defaultPodOptions:
          automountServiceAccountToken: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: {type: RuntimeDefault}
    persistence:
      config:
        enabled: true
        existingClaim: tachidesk-config
        globalMounts:
        - path: /home/suwayomi/.local/share/Tachidesk
      downloads:
        enabled: true
        globalMounts:
        - path: /mnt
        path: /mnt/main/manga-share
        server: nas.dot-hex.xyz
        type: nfs
    service:
      app:
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dot-hex.xyz"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
