# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Glnu1B5M2qxgMfkahJ7QDbJj+rh5GJhZLPu0ypX5e3KnBEXaWKaB+w==,iv:QH3dayE2vFDAQzSNm2v4e9SsGDHGUZGc7xjAHareAqw=,tag:l/hWpBzeNeu8WFADFUSblQ==,type:str]
sops:
  age:
    - recipient: age1qzzw37sv7ctnmgv6jlu5k8063y5drskzzdwzvz3fc05vkwsuxefq7wwqxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNlVrVm5odnpseHIvalFV
        U3FLRXYyeVJ4UnhvR0hOVk1XbzBhQ2NpT1FVClFVaFFoSjEvOEpBVE5RZHdjU0RV
        R1dKMmFBcWFQb09GcTJRUDZmcjRYaVUKLS0tIEdqeFdjZHBXMnorbFN3aVJ2ZUJX
        WW1Wb2x6R2hpaEJ4TlhnNU8ySmZTd1EKykhX2CRj3zCkMKW7ZBbzqQNOjhOTzTiB
        NEohr4PxtzIP7nwULbBeK0vDh9hiqnPbZMf79RaCj1U88f7vEsWNlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-11T09:27:36Z"
  mac: ENC[AES256_GCM,data:hDRserf76nGp7jHM9NX1K1pCcUt2kcQokyuF0lgsmGcT8uMohwJpwvzQitDua/bg0mDnCiuPyj9zQ+oxHqDZ3JKgfPzMexQcPRFhBAr2TH202EQtKcmQJu/Rhga7oaocTYtiM7BvpZ8bptOov449HPwGCR+gbLs16yFekhAurWo=,iv:w9RfrfD9fWM6cFxm3efhnOiMEXpFav+BoJmK4TXebw0=,tag:5ONZz31EUON2yctDiozKpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
