---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: roundcube
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      data:
        ROUNDCUBEMAIL_DEFAULT_HOST: "{{ .ROUNDCUBEMAIL_DEFAULT_HOST }}"
        ROUNDCUBEMAIL_DEFAULT_PORT: "{{ .ROUNDCUBEMAIL_DEFAULT_PORT }}"
        ROUNDCUBEMAIL_SMTP_SERVER: "{{ .ROUNDCUBEMAIL_SMTP_SERVER }}"
        ROUNDCUBEMAIL_SMTP_PORT: "{{ .ROUNDCUBEMAIL_SMTP_PORT }}"
  dataFrom:
    - extract:
        key: roundcube
