---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
spec:
  interval: 30m
  url: https://charts.longhorn.io
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.6.1
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: longhorn
  interval: 30m0s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultSettings:
      backupstorePollInterval: 0
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultDataPath: /var/lib/rancher/k3s/longhorn
      defaultLonghornStaticStorageClass: longhorn
      defaultReplicaCount: 3
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      orphanAutoDeletion: true
      restoreVolumeRecurringJobs: true
      storageMinimalAvailablePercentage: 10
      storageOverProvisioningPercentage: 200
    route:
      main:
        enabled: true
        hostnames:
          - "longhorn-2.dot-hex.xyz"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
        - backendRefs:
          - name: longhorn-frontend
            port: 80
