---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pairdrop
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m0s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      pairdrop:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository:  ghcr.io/schlagmichdoch/pairdrop
              tag: v1.11.2
            probes:
              liveness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /manifest.json
                    port: &port 3000
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness:
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /manifest.json
                    port: *port
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 1
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 10m
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 65539
    service:
      app:
        ports:
          http:
            port: *port
        type: ClusterIP
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dot-hex.xyz"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
