apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:VzL57AgfzDPy8GQ=,iv:iCpdKvENsMZuL1wO/4uRSe8C91AZMn13rIicARaE98U=,tag:mWz9+MW3mPeWqYb3+BHqEw==,type:str]
sops:
  age:
    - recipient: age1qzzw37sv7ctnmgv6jlu5k8063y5drskzzdwzvz3fc05vkwsuxefq7wwqxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTHp3bHhlZWpBTllXTVpU
        eHNPdFVQemY3WlI4MGRYdWViMEtHTVZQR3dNCmc0cUdYRWNlNVY1VXArV21tVkZP
        R1QyRm5lZ3JIUzRnb3dZMElEN0N6ZTQKLS0tICtpaE92WXFURDJDMlNSTk92ZW5l
        VEtuVFFnUDJmd1hPMHJGR1l3VzlHdUEK5jVpy1w+Othq1ZWBjwwiqR45qflPidMG
        L/pHQj/vfXGIWkgjW5Mf9/lCDYOOjpG45j09urwKFYHQsLb8Z2bOaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-05T09:55:40Z"
  mac: ENC[AES256_GCM,data:68SbfSE57CCITBkXuy51XEQ0qdxOJmiPp8ZNcfCzYKHIzyd7LdWF/zE3CXg1HWzSsywj4HNuQQwhKIwBcXvdiMZSQkfzwE3IqP5/fN1nVa49p2xBSQlJzR9Hc6YURuVr6jGcUFx3+jteB45K23HgS2ZejmcrkkdQeAx4rwZBdiA=,iv:I8hrYlEY4SJy2Moi2hiq4cnXquqwG/hFRDnQ5yxlEYs=,tag:2OUMLSQiYXj5XM4LZCW5cQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
