apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:ozw3FtAXhtqvA30RXSpDRhCgL049uO1yfzP2vQDzXxI+P5rXxbLbfdD/1oeY1+NrvuEEndItNsLRNaEQpATb35IF37KLCQhY+ZA=,iv:++wWEku+mTav8OJOlNE/pBkC697Wg2NslbiKFO74BG8=,tag:0Kici0hGebdwzG6inbaZIg==,type:str]
sops:
  age:
    - recipient: age1qzzw37sv7ctnmgv6jlu5k8063y5drskzzdwzvz3fc05vkwsuxefq7wwqxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR2Q4MWE0YzhMR2wvODdj
        bk5KY0l2eEltbER0emVhVk1sMHR0VzBoYTBNCkFtelc3M3FtUE94bXBrak1JcWxo
        WkdhWlk2NUlxOXl0SThlbGdsOElyT3cKLS0tIERQckxlQTN5TlZIdjVVaUpKamw3
        NmlJL2pmNVRST1BsV0lGZkppU0QwcGcKcU1mVkYEC3HJDNa83U3ym1hL7oCUYrZJ
        l3B/gUnX+ZoRs1rBnSK/MKbHEDqnP4FebIvMsNvC7PLseZEFBmBd3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T08:41:54Z"
  mac: ENC[AES256_GCM,data:5m09xH7TykfkNXxjArT2bNKz5Q6Mq3eA5xyEzswbdI0D2B731bWOg63anF4ZeD9AFG+QBp7kdVgMoq+H3whrD4TE125A82m9ErRdY+x58dGhPMNM3gEdqrY1aEkIUJf1sd7lXzhy9RceWo9Z3Mf9PO8Qk96o9HQj2UaBC/2kXd0=,iv:d21dQUgKjavaamkEhB8Km8LICVMQRnkhsyOZQ3QKMpw=,tag:b52u5k+F4y4/8MB5CSoefA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
