apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:bqmHuJ5rBfOcJb+8dvM4zSWgW7WWOtR8Zb/aA94waVw2ktfDWdz2jYu8Ta2bHTGdZdPNRE2RhTf60balCD/HvBEwlgZ8wKiWdo4=,iv:8qLTpP/w7GN3KpNOMeoLwEJDAlMAviVgmGSk57xPxsE=,tag:g9sJICkudjlfx2bjv4lJNA==,type:str]
sops:
  age:
    - recipient: age1qzzw37sv7ctnmgv6jlu5k8063y5drskzzdwzvz3fc05vkwsuxefq7wwqxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QlJ3ZkpVd1BRYWlMUzha
        ZTdKZk5tYmEvc3Q2ajlhb3ZEZEhqcjh6RXo4CkRPaUFjV0FJSE1JZ2IzSGFIUG5Q
        ek1iUWIxQ0lJcW8yZnM4R3lLZngxWnMKLS0tIDBaS0FEUGdnM2l6bEpPei83UVUv
        c3l2MWQrdXlTcFpCWTNDcU5UcTdTMk0KUFWTItYlI9QuwqJUpWiW2KnTX4bcI/cy
        aPqvXvDrPDLV4NwuXcTfsckh/qQ6bB72w/ebNhGFBQyzVVn8AhgprQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-05T09:55:40Z"
  mac: ENC[AES256_GCM,data:Pf3ag6NdyMVmc68RhKNpu4kfxtQ05q3wnJYWdLNcIf/Q7mQDpwmkFZJYk1f3QmqPImVemY3GVjXf6zZ+aQq7/gBSLl7JoN/5Sb8q5UN15kuKg+uFBU2YXUDKq1qMlLKsjPGjb5qPTB1vsrDJfS4SWYtEt5B+b9l5RO5P4YLYTEE=,iv:Q2FB8qR8BSA2+sLkRSevQAZS3aO3wkj/0W53dpshH5c=,tag:+kq3YT/Jr6z6TyRAThOt6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
